### ISSUE TITLE
Prevent the background color from being reset when the offset values are updated

### ISSUE THREAD

**Issue by Cuperino** [michel-iwaniec/OverlayPal#55]
# Problem

I've composed an image that didn't break any of the NES' composition rules, but because I wasn't setting the correct background color and pixel offset, OverlayPal wasn't able to find a solution to my background.

Each time I offset the image, the background is reset to its default unnecessarily. Sometimes I didn't notice that the background color had been reset and tested the offset with the wrong background color, which resulted in the right offset failing to find a solution.

# Suggestion

- Prevent the background color from being reset when the offset values are updated.

**Comment by michel-iwaniec** [comment]
Fixed in https://github.com/michel-iwaniec/OverlayPal/pull/60 by introducing a new checkbox "Force Background Color" that keeps the user-selected color

(auto-detection is still the default, and indicated clearly in the comboxbox with an "auto: " prefix)
